### ISSUE TITLE
Misskey fails to install

### ISSUE THREAD

**Issue by spctrlth** [YunoHost-Apps/misskey_ynh#21]
### Describe the bug

Hey, I tried to install Misskey, but it failed. It was just to check out, so no biggy, but I thought I should at least report it anyways.

### Context

- Hardware: Old laptop
- YunoHost version: 4.2.6.1
- I have access to my server: Through SSH and through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: N/A
- Using, or trying to install package version/branch: trying to install misskey
- If upgrading, current package version: N/A

### Steps to reproduce

    ```sh
    sudo su -
    yunohost app install misskey
    ```
### Expected behavior

It installs :)

### Logs

ynh log: https://paste.yunohost.org/raw/cemewocaci

npm log:

```
root@spectraltheorem:~# cat /root/.npm/_logs/2021-08-02T18_11_56_868Z-debug.log 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/node_n/n/versions/node/12.22.4/bin/node',
1 verbose cli   '/opt/node_n/n/versions/node/12/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build-webpack'
1 verbose cli ]
2 info using npm@6.14.14
3 info using node@v12.22.4
4 verbose run-script [ 'prebuild-webpack', 'build-webpack', 'postbuild-webpack' ]
5 info lifecycle misskey@12.83.0~prebuild-webpack: misskey@12.83.0
6 info lifecycle misskey@12.83.0~build-webpack: misskey@12.83.0
7 warn lifecycle The node binary used for scripts is /tmp/yarn--1627927911645-0.8918027157145176/node but npm is using /opt/node_n/n/versions/node/12.22.4/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle misskey@12.83.0~build-webpack: unsafe-perm in lifecycle true
9 verbose lifecycle misskey@12.83.0~build-webpack: PATH: /opt/node_n/n/versions/node/12.22.4/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/var/www/misskey/node_modules/.bin:/tmp/yarn--1627927911645-0.8918027157145176:/var/www/misskey/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/opt/node_n/n/versions/node/12.22.4/libexec/lib/node_modules/npm/bin/node-gyp-bin:/opt/node_n/n/versions/node/12.22.4/lib/node_modules/npm/bin/node-gyp-bin:/opt/node_n/n/versions/node/12.22.4/bin/node_modules/npm/bin/node-gyp-bin:/opt/node_n/n/versions/node/12/bin:/opt/node_n/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle misskey@12.83.0~build-webpack: CWD: /var/www/misskey
11 silly lifecycle misskey@12.83.0~build-webpack: Args: [ '-c', 'webpack' ]
12 silly lifecycle misskey@12.83.0~build-webpack: Returned: code: 2  signal: null
13 info lifecycle misskey@12.83.0~build-webpack: Failed to exec build-webpack script
14 verbose stack Error: misskey@12.83.0 build-webpack: `webpack`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (/opt/node_n/n/versions/node/12.22.4/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:314:20)
14 verbose stack     at ChildProcess.<anonymous> (/opt/node_n/n/versions/node/12.22.4/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:314:20)
14 verbose stack     at maybeClose (internal/child_process.js:1022:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
15 verbose pkgid misskey@12.83.0
16 verbose cwd /var/www/misskey
17 verbose Linux 4.19.0-17-amd64
18 verbose argv "/opt/node_n/n/versions/node/12.22.4/bin/node" "/opt/node_n/n/versions/node/12/bin/npm" "run" "build-webpack"
19 verbose node v12.22.4
20 verbose npm  v6.14.14
21 error code ELIFECYCLE
22 error errno 2
23 error misskey@12.83.0 build-webpack: `webpack`
23 error Exit status 2
24 error Failed at the misskey@12.83.0 build-webpack script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 2, true ]
root@spectraltheorem:~# 
```

**Comment by lapineige** [comment]
Same issue I think, here is some more details in the log:

```
yarn run v1.22.5
2021-08-11 15:38:37,052: DEBUG - $ npm run build-webpack && npm run build-ts && npm run build-gulp
2021-08-11 15:38:37,522: DEBUG - npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1628689117063-0.20871137737880674/node but npm is using /opt/node_n/n/versions/node/12.22.3/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
2021-08-11 15:38:37,525: DEBUG - 
2021-08-11 15:38:37,525: DEBUG - > misskey@12.84.2 build-webpack /var/www/misskey
2021-08-11 15:38:37,525: DEBUG - > webpack
2021-08-11 15:38:37,525: DEBUG - 
2021-08-11 15:38:42,065: DEBUG - [webpack-cli] Failed to load '/var/www/misskey/webpack.config.ts' config
2021-08-11 15:38:42,221: DEBUG - [webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
2021-08-11 15:38:42,222: DEBUG - Require stack:
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/vue-loader/dist/pluginWebpack5.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/vue-loader/dist/plugin.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/vue-loader/dist/index.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/webpack.config.ts
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/webpack-cli/lib/webpack-cli.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/webpack-cli/lib/bootstrap.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/webpack-cli/bin/cli.js
    2021-08-11 15:38:42,222: DEBUG - - /var/www/misskey/node_modules/webpack/bin/webpack.js
    2021-08-11 15:38:42,222: DEBUG -     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    2021-08-11 15:38:42,222: DEBUG -     at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    2021-08-11 15:38:42,222: DEBUG -     at Module.require (internal/modules/cjs/loader.js:887:19)
    2021-08-11 15:38:42,222: DEBUG -     at require (/var/www/misskey/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    2021-08-11 15:38:42,223: DEBUG -     at Object.<anonymous> (/var/www/misskey/node_modules/vue-loader/dist/pluginWebpack5.js:9:42)
    2021-08-11 15:38:42,223: DEBUG -     at Module._compile (/var/www/misskey/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    2021-08-11 15:38:42,223: DEBUG -     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    2021-08-11 15:38:42,223: DEBUG -     at Module.load (internal/modules/cjs/loader.js:863:32)
    2021-08-11 15:38:42,223: DEBUG -     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    2021-08-11 15:38:42,223: DEBUG -     at Module.require (internal/modules/cjs/loader.js:887:19) {
        2021-08-11 15:38:42,223: DEBUG -   code: 'MODULE_NOT_FOUND',
        2021-08-11 15:38:42,223: DEBUG -   requireStack: [
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/node_modules/vue-loader/dist/pluginWebpack5.js',
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/node_modules/vue-loader/dist/plugin.js',
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/node_modules/vue-loader/dist/index.js',
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/webpack.config.ts',
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/node_modules/webpack-cli/lib/webpack-cli.js',
            2021-08-11 15:38:42,223: DEBUG -     '/var/www/misskey/node_modules/webpack-cli/lib/bootstrap.js',
            2021-08-11 15:38:42,224: DEBUG -     '/var/www/misskey/node_modules/webpack-cli/bin/cli.js',
            2021-08-11 15:38:42,224: DEBUG -     '/var/www/misskey/node_modules/webpack/bin/webpack.js'
            2021-08-11 15:38:42,224: DEBUG -   ]
        2021-08-11 15:38:42,224: DEBUG - }
        2021-08-11 15:38:42,250: DEBUG - npm ERR! code ELIFECYCLE
        2021-08-11 15:38:42,250: DEBUG - npm ERR! errno 2
        2021-08-11 15:38:42,254: DEBUG - npm ERR! misskey@12.84.2 build-webpack: `webpack`
        2021-08-11 15:38:42,255: DEBUG - npm ERR! Exit status 2
        2021-08-11 15:38:42,255: DEBUG - npm ERR!
        2021-08-11 15:38:42,255: DEBUG - npm ERR! Failed at the misskey@12.84.2 build-webpack script.
        2021-08-11 15:38:42,255: DEBUG - npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by lapineige** [comment]
While trying again: 

> 
DEBUG sudo --login --user=postgres PGUSER=postgres PGPASSWORD=********** psql -tAc 'SELECT rolname FROM pg_roles WHERE rolname='\''misskey'\'';'
DEBUG - + return 0
DEBUG - + '[' -z ']'
DEBUG - + ynh_die '--message=The user misskey exists, please provide his password'

It seems that it did not delete the postgreSQL user…

**Comment by ericgaspar** [comment]
closing. Please reopen an issue if you still have this issue.
